import { addDays, startOfWeek, setHours, setMinutes } from 'date-fns';
import type {
  Agent,
  Team,
  Ticket,
  Appointment,
  WorkingHours,
} from '@/types';

// Helper to create standard working hours (Mon-Fri, 8AM-5PM)
const standardWorkingHours: WorkingHours = {
  monday: { isWorking: true, startTime: '08:00', endTime: '17:00' },
  tuesday: { isWorking: true, startTime: '08:00', endTime: '17:00' },
  wednesday: { isWorking: true, startTime: '08:00', endTime: '17:00' },
  thursday: { isWorking: true, startTime: '08:00', endTime: '17:00' },
  friday: { isWorking: true, startTime: '08:00', endTime: '17:00' },
  saturday: { isWorking: false, startTime: '00:00', endTime: '00:00' },
  sunday: { isWorking: false, startTime: '00:00', endTime: '00:00' },
};

// Demo Teams
export const demoTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Service/Desktop',
    description: 'Desktop support and service team',
    memberIds: [1, 2, 6],
    color: '#3b82f6', // blue
    isActive: true,
    sequence: 1,
  },
  {
    id: 'team-2',
    name: 'Network Team',
    description: 'Network infrastructure and connectivity',
    memberIds: [3, 4],
    color: '#10b981', // green
    isActive: true,
    sequence: 2,
  },
  {
    id: 'team-3',
    name: 'Internal Team',
    description: 'Internal IT support',
    memberIds: [5],
    color: '#f59e0b', // amber
    isActive: true,
    sequence: 3,
  },
];

// Demo Agents
export const demoAgents: Agent[] = [
  {
    id: 1,
    name: 'Andy Bell',
    email: 'andy.bell@company.com',
    phone: '555-0101',
    initials: 'AB',
    role: 'System and Sales Engineer',
    teamIds: ['team-1'],
    skills: ['Desktop Support', 'Sales', 'Onboarding'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#3b82f6',
  },
  {
    id: 2,
    name: 'Test User',
    email: 'test.user@company.com',
    phone: '555-0102',
    initials: 'TU',
    role: 'System and Sales Engineer',
    teamIds: ['team-1'],
    skills: ['Desktop Support', 'Testing', 'Documentation'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#8b5cf6',
  },
  {
    id: 3,
    name: 'Jeff Graham',
    email: 'jeff.graham@company.com',
    phone: '555-0103',
    initials: 'JG',
    role: 'Network Specialist',
    teamIds: ['team-2'],
    skills: ['Networking', 'Firewall', 'VPN'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#10b981',
  },
  {
    id: 4,
    name: 'Bill South',
    email: 'bill.south@company.com',
    phone: '555-0104',
    initials: 'BS',
    role: 'Senior Network Engineer',
    teamIds: ['team-2'],
    skills: ['Networking', 'Security', 'Infrastructure'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#06b6d4',
  },
  {
    id: 5,
    name: 'Chris Craft',
    email: 'chris.craft@company.com',
    phone: '555-0105',
    initials: 'CC',
    role: 'Internal IT Support',
    teamIds: ['team-3'],
    skills: ['Internal Support', 'Hardware', 'Software'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#f59e0b',
  },
  {
    id: 6,
    name: 'Brown Bufford',
    email: 'brown.bufford@company.com',
    phone: '555-0106',
    initials: 'BB',
    role: 'Junior Technician',
    teamIds: ['team-1'],
    skills: ['Desktop Support', 'Troubleshooting'],
    workingHours: standardWorkingHours,
    isActive: true,
    color: '#ec4899',
  },
];

// Demo Tickets
const baseDate = startOfWeek(new Date(), { weekStartsOn: 1 });

export const demoTickets: Ticket[] = [
  {
    id: 'ticket-1',
    ticketNumber: 'T-2831',
    title: 'ConnectWise Weekly Team Meeting',
    description: 'Weekly team sync meeting for ConnectWise project',
    status: 'scheduled',
    priority: 'medium',
    customerName: 'Internal',
    customerEmail: 'team@company.com',
    siteName: 'Main Office',
    category: 'Internal',
    tags: ['meeting', 'weekly', 'connectwise'],
    createdAt: addDays(baseDate, -7),
    updatedAt: addDays(baseDate, -1),
    estimatedDuration: 60,
  },
  {
    id: 'ticket-2',
    ticketNumber: 'T-2811',
    title: 'Atlantic Northern Meeting setup',
    description: 'Setup conference room for Atlantic Northern client meeting',
    status: 'scheduled',
    priority: 'high',
    customerName: 'Atlantic Northern',
    customerEmail: 'contact@atlanticnorthern.com',
    siteName: 'Conference Room A',
    category: 'Onboarding Projects',
    tags: ['setup', 'meeting', 'client'],
    createdAt: addDays(baseDate, -5),
    updatedAt: addDays(baseDate, -2),
    estimatedDuration: 30,
  },
  {
    id: 'ticket-3',
    ticketNumber: 'T-342',
    title: 'Chris Craft Boats Weekly Sales',
    description: 'Weekly sales review meeting for Chris Craft Boats account',
    status: 'scheduled',
    priority: 'medium',
    customerName: 'Chris Craft Boats',
    customerEmail: 'sales@chriscraftboats.com',
    siteName: 'Client Site',
    category: 'Service Projects',
    tags: ['sales', 'weekly', 'boats'],
    createdAt: addDays(baseDate, -10),
    updatedAt: addDays(baseDate, -3),
    estimatedDuration: 45,
  },
  {
    id: 'ticket-4',
    ticketNumber: 'T-282',
    title: 'Chris Craft Boats Create Router Maintenance',
    description: 'Perform routine maintenance on router infrastructure',
    status: 'scheduled',
    priority: 'medium',
    customerName: 'Chris Craft Boats',
    customerEmail: 'it@chriscraftboats.com',
    siteName: 'Client Site',
    category: 'Network Projects',
    tags: ['maintenance', 'router', 'network'],
    createdAt: addDays(baseDate, -8),
    updatedAt: addDays(baseDate, -2),
    estimatedDuration: 120,
  },
  {
    id: 'ticket-5',
    ticketNumber: 'T-482',
    title: 'Brown Bufford and What Virtual Domain Controller',
    description: 'Setup and configure virtual domain controller',
    status: 'scheduled',
    priority: 'high',
    customerName: 'Brown Bufford and What',
    customerEmail: 'admin@brownbufford.com',
    siteName: 'Data Center',
    category: 'Service Projects',
    tags: ['virtualization', 'domain controller', 'setup'],
    createdAt: addDays(baseDate, -6),
    updatedAt: addDays(baseDate, -1),
    estimatedDuration: 180,
  },
  {
    id: 'ticket-6',
    ticketNumber: 'T-582',
    title: 'Butler Attorneys My Company Sites Law Firm',
    description: 'Setup company website for law firm client',
    status: 'scheduled',
    priority: 'medium',
    customerName: 'Butler Attorneys',
    customerEmail: 'contact@butlerattorneys.com',
    siteName: 'Law Office',
    category: 'Onboarding Projects',
    tags: ['website', 'setup', 'law firm'],
    createdAt: addDays(baseDate, -4),
    updatedAt: addDays(baseDate, -1),
    estimatedDuration: 90,
  },
  {
    id: 'ticket-7',
    ticketNumber: 'T-682',
    title: 'Acme IT Solutions Demo & IT Seats',
    description: 'Product demonstration and IT seat configuration',
    status: 'scheduled',
    priority: 'low',
    customerName: 'Acme IT Solutions',
    customerEmail: 'demo@acmeit.com',
    siteName: 'Demo Room',
    category: 'Offboarding Projects',
    tags: ['demo', 'configuration', 'seats'],
    createdAt: addDays(baseDate, -3),
    updatedAt: addDays(baseDate, -1),
    estimatedDuration: 60,
  },
  {
    id: 'ticket-8',
    ticketNumber: 'T-785',
    title: 'Chris Craft Boats Initial Server',
    description: 'Initial server setup and configuration',
    status: 'scheduled',
    priority: 'urgent',
    customerName: 'Chris Craft Boats',
    customerEmail: 'it@chriscraftboats.com',
    siteName: 'Server Room',
    category: 'Service Projects',
    tags: ['server', 'setup', 'initial'],
    createdAt: addDays(baseDate, -2),
    updatedAt: new Date(),
    estimatedDuration: 240,
  },
  {
    id: 'ticket-9',
    ticketNumber: 'T-101',
    title: 'New Client Onboarding',
    description: 'Complete onboarding process for new client',
    status: 'new',
    priority: 'high',
    customerName: 'XYZ Company',
    customerEmail: 'onboarding@xyz.com',
    siteName: 'Client Office',
    category: 'Onboarding Projects',
    tags: ['onboarding', 'new client'],
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedDuration: 120,
  },
  {
    id: 'ticket-10',
    ticketNumber: 'T-102',
    title: 'Network Troubleshooting',
    description: 'Investigate intermittent network connectivity issues',
    status: 'in_progress',
    priority: 'urgent',
    customerName: 'ABC Corporation',
    customerEmail: 'it@abc.com',
    siteName: 'Main Office',
    category: 'Network Projects',
    tags: ['network', 'troubleshooting', 'urgent'],
    createdAt: addDays(new Date(), -1),
    updatedAt: new Date(),
    estimatedDuration: 90,
  },
  {
    id: 'ticket-11',
    ticketNumber: 'T-103',
    title: 'Software Installation',
    description: 'Install and configure accounting software on 5 workstations',
    status: 'new',
    priority: 'medium',
    customerName: 'Finance Plus',
    customerEmail: 'support@financeplus.com',
    siteName: 'Accounting Department',
    category: 'Service Projects',
    tags: ['software', 'installation'],
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedDuration: 150,
  },
  {
    id: 'ticket-12',
    ticketNumber: 'T-104',
    title: 'Email Migration',
    description: 'Migrate 50 mailboxes from on-premise Exchange to Office 365',
    status: 'new',
    priority: 'high',
    customerName: 'Global Industries',
    customerEmail: 'admin@globalind.com',
    siteName: 'Corporate HQ',
    category: 'Service Projects',
    tags: ['email', 'migration', 'office365'],
    createdAt: addDays(new Date(), -2),
    updatedAt: new Date(),
    estimatedDuration: 360,
  },
  {
    id: 'ticket-13',
    ticketNumber: 'T-105',
    title: 'Printer Setup',
    description: 'Configure new network printer in Marketing department',
    status: 'new',
    priority: 'low',
    customerName: 'Marketing Pro',
    customerEmail: 'it@marketingpro.com',
    siteName: 'Marketing Floor',
    category: 'Service Projects',
    tags: ['printer', 'setup', 'hardware'],
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedDuration: 30,
  },
  {
    id: 'ticket-14',
    ticketNumber: 'T-106',
    title: 'Security Audit',
    description: 'Conduct comprehensive security audit and generate report',
    status: 'new',
    priority: 'high',
    customerName: 'Secure Systems Inc',
    customerEmail: 'security@securesys.com',
    siteName: 'All Locations',
    category: 'Network Projects',
    tags: ['security', 'audit', 'compliance'],
    createdAt: addDays(new Date(), -3),
    updatedAt: new Date(),
    estimatedDuration: 480,
  },
  {
    id: 'ticket-15',
    ticketNumber: 'T-107',
    title: 'Backup System Configuration',
    description: 'Setup automated backup system for critical servers',
    status: 'new',
    priority: 'urgent',
    customerName: 'Data Safe Co',
    customerEmail: 'admin@datasafe.com',
    siteName: 'Data Center',
    category: 'Service Projects',
    tags: ['backup', 'configuration', 'critical'],
    createdAt: new Date(),
    updatedAt: new Date(),
    estimatedDuration: 180,
  },
];

// Demo Appointments
export const demoAppointments: Appointment[] = [
  {
    id: 'apt-1',
    ticketId: 'ticket-1',
    ticket: demoTickets[0],
    agentId: 1,
    startTime: setMinutes(setHours(addDays(baseDate, 0), 7), 30),
    endTime: setMinutes(setHours(addDays(baseDate, 0), 8), 30),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -5),
    updatedAt: addDays(baseDate, -1),
  },
  {
    id: 'apt-2',
    ticketId: 'ticket-2',
    ticket: demoTickets[1],
    agentId: 3,
    startTime: setHours(addDays(baseDate, 0), 8),
    endTime: setMinutes(setHours(addDays(baseDate, 0), 8), 30),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -4),
    updatedAt: addDays(baseDate, -2),
  },
  {
    id: 'apt-3',
    ticketId: 'ticket-3',
    ticket: demoTickets[2],
    agentId: 1,
    startTime: setHours(addDays(baseDate, 0), 8),
    endTime: setMinutes(setHours(addDays(baseDate, 0), 8), 45),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -6),
    updatedAt: addDays(baseDate, -3),
  },
  {
    id: 'apt-4',
    ticketId: 'ticket-4',
    ticket: demoTickets[3],
    agentId: 2,
    startTime: setHours(addDays(baseDate, 1), 8),
    endTime: setHours(addDays(baseDate, 1), 10),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -5),
    updatedAt: addDays(baseDate, -2),
  },
  {
    id: 'apt-5',
    ticketId: 'ticket-5',
    ticket: demoTickets[4],
    agentId: 1,
    startTime: setHours(addDays(baseDate, 1), 10),
    endTime: setHours(addDays(baseDate, 1), 13),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -4),
    updatedAt: addDays(baseDate, -1),
  },
  {
    id: 'apt-6',
    ticketId: 'ticket-6',
    ticket: demoTickets[5],
    agentId: 3,
    startTime: setMinutes(setHours(addDays(baseDate, 3), 8), 0),
    endTime: setMinutes(setHours(addDays(baseDate, 3), 9), 30),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -3),
    updatedAt: addDays(baseDate, -1),
  },
  {
    id: 'apt-7',
    ticketId: 'ticket-7',
    ticket: demoTickets[6],
    agentId: 4,
    startTime: setHours(addDays(baseDate, 4), 8),
    endTime: setHours(addDays(baseDate, 4), 9),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -2),
    updatedAt: addDays(baseDate, -1),
  },
  {
    id: 'apt-8',
    ticketId: 'ticket-8',
    ticket: demoTickets[7],
    agentId: 2,
    startTime: setHours(addDays(baseDate, 4), 8),
    endTime: setHours(addDays(baseDate, 4), 12),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -1),
    updatedAt: new Date(),
  },
  // Add more appointments for different agents
  {
    id: 'apt-9',
    ticketId: 'ticket-1',
    ticket: demoTickets[0],
    agentId: 5,
    startTime: setHours(addDays(baseDate, 0), 9),
    endTime: setHours(addDays(baseDate, 0), 10),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -5),
    updatedAt: addDays(baseDate, -1),
  },
  {
    id: 'apt-10',
    ticketId: 'ticket-2',
    ticket: demoTickets[1],
    agentId: 6,
    startTime: setHours(addDays(baseDate, 0), 8),
    endTime: setMinutes(setHours(addDays(baseDate, 0), 8), 30),
    status: 'scheduled',
    isAllDay: false,
    isTentative: false,
    createdAt: addDays(baseDate, -4),
    updatedAt: addDays(baseDate, -2),
  },
];
